// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.3
// source: proto/services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceOneClient is the client API for ServiceOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceOneClient interface {
	Example(ctx context.Context, in *ExampleMessage, opts ...grpc.CallOption) (*ExampleMessage, error)
}

type serviceOneClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceOneClient(cc grpc.ClientConnInterface) ServiceOneClient {
	return &serviceOneClient{cc}
}

func (c *serviceOneClient) Example(ctx context.Context, in *ExampleMessage, opts ...grpc.CallOption) (*ExampleMessage, error) {
	out := new(ExampleMessage)
	err := c.cc.Invoke(ctx, "/B1scuit.otel_go_grpc.ServiceOne/Example", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceOneServer is the server API for ServiceOne service.
// All implementations must embed UnimplementedServiceOneServer
// for forward compatibility
type ServiceOneServer interface {
	Example(context.Context, *ExampleMessage) (*ExampleMessage, error)
	mustEmbedUnimplementedServiceOneServer()
}

// UnimplementedServiceOneServer must be embedded to have forward compatible implementations.
type UnimplementedServiceOneServer struct {
}

func (UnimplementedServiceOneServer) Example(context.Context, *ExampleMessage) (*ExampleMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Example not implemented")
}
func (UnimplementedServiceOneServer) mustEmbedUnimplementedServiceOneServer() {}

// UnsafeServiceOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceOneServer will
// result in compilation errors.
type UnsafeServiceOneServer interface {
	mustEmbedUnimplementedServiceOneServer()
}

func RegisterServiceOneServer(s grpc.ServiceRegistrar, srv ServiceOneServer) {
	s.RegisterService(&ServiceOne_ServiceDesc, srv)
}

func _ServiceOne_Example_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOneServer).Example(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/B1scuit.otel_go_grpc.ServiceOne/Example",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOneServer).Example(ctx, req.(*ExampleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceOne_ServiceDesc is the grpc.ServiceDesc for ServiceOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "B1scuit.otel_go_grpc.ServiceOne",
	HandlerType: (*ServiceOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Example",
			Handler:    _ServiceOne_Example_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services.proto",
}

// ServiceTwoClient is the client API for ServiceTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceTwoClient interface {
	Example(ctx context.Context, in *ExampleMessage, opts ...grpc.CallOption) (*ExampleMessage, error)
}

type serviceTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceTwoClient(cc grpc.ClientConnInterface) ServiceTwoClient {
	return &serviceTwoClient{cc}
}

func (c *serviceTwoClient) Example(ctx context.Context, in *ExampleMessage, opts ...grpc.CallOption) (*ExampleMessage, error) {
	out := new(ExampleMessage)
	err := c.cc.Invoke(ctx, "/B1scuit.otel_go_grpc.ServiceTwo/Example", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceTwoServer is the server API for ServiceTwo service.
// All implementations must embed UnimplementedServiceTwoServer
// for forward compatibility
type ServiceTwoServer interface {
	Example(context.Context, *ExampleMessage) (*ExampleMessage, error)
	mustEmbedUnimplementedServiceTwoServer()
}

// UnimplementedServiceTwoServer must be embedded to have forward compatible implementations.
type UnimplementedServiceTwoServer struct {
}

func (UnimplementedServiceTwoServer) Example(context.Context, *ExampleMessage) (*ExampleMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Example not implemented")
}
func (UnimplementedServiceTwoServer) mustEmbedUnimplementedServiceTwoServer() {}

// UnsafeServiceTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceTwoServer will
// result in compilation errors.
type UnsafeServiceTwoServer interface {
	mustEmbedUnimplementedServiceTwoServer()
}

func RegisterServiceTwoServer(s grpc.ServiceRegistrar, srv ServiceTwoServer) {
	s.RegisterService(&ServiceTwo_ServiceDesc, srv)
}

func _ServiceTwo_Example_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceTwoServer).Example(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/B1scuit.otel_go_grpc.ServiceTwo/Example",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceTwoServer).Example(ctx, req.(*ExampleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceTwo_ServiceDesc is the grpc.ServiceDesc for ServiceTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "B1scuit.otel_go_grpc.ServiceTwo",
	HandlerType: (*ServiceTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Example",
			Handler:    _ServiceTwo_Example_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services.proto",
}

// ServiceThreeClient is the client API for ServiceThree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceThreeClient interface {
	Example(ctx context.Context, in *ExampleMessage, opts ...grpc.CallOption) (*ExampleMessage, error)
}

type serviceThreeClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceThreeClient(cc grpc.ClientConnInterface) ServiceThreeClient {
	return &serviceThreeClient{cc}
}

func (c *serviceThreeClient) Example(ctx context.Context, in *ExampleMessage, opts ...grpc.CallOption) (*ExampleMessage, error) {
	out := new(ExampleMessage)
	err := c.cc.Invoke(ctx, "/B1scuit.otel_go_grpc.ServiceThree/Example", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceThreeServer is the server API for ServiceThree service.
// All implementations must embed UnimplementedServiceThreeServer
// for forward compatibility
type ServiceThreeServer interface {
	Example(context.Context, *ExampleMessage) (*ExampleMessage, error)
	mustEmbedUnimplementedServiceThreeServer()
}

// UnimplementedServiceThreeServer must be embedded to have forward compatible implementations.
type UnimplementedServiceThreeServer struct {
}

func (UnimplementedServiceThreeServer) Example(context.Context, *ExampleMessage) (*ExampleMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Example not implemented")
}
func (UnimplementedServiceThreeServer) mustEmbedUnimplementedServiceThreeServer() {}

// UnsafeServiceThreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceThreeServer will
// result in compilation errors.
type UnsafeServiceThreeServer interface {
	mustEmbedUnimplementedServiceThreeServer()
}

func RegisterServiceThreeServer(s grpc.ServiceRegistrar, srv ServiceThreeServer) {
	s.RegisterService(&ServiceThree_ServiceDesc, srv)
}

func _ServiceThree_Example_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceThreeServer).Example(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/B1scuit.otel_go_grpc.ServiceThree/Example",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceThreeServer).Example(ctx, req.(*ExampleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceThree_ServiceDesc is the grpc.ServiceDesc for ServiceThree service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceThree_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "B1scuit.otel_go_grpc.ServiceThree",
	HandlerType: (*ServiceThreeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Example",
			Handler:    _ServiceThree_Example_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services.proto",
}
